// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { default_language: string, update_interval_minutes: bigint, content_ratings: Array<string>, user_agent: string, theme: string, reader_mode: string, reader_layout: string, reader_fit: string, api_token: string | null, mal_client_id: string | null, hide_empty_uncategorized: boolean, mal_sync_on_read: boolean, mal_sync_on_complete: boolean, mal_ask_before_sync: boolean, mal_sync_score: boolean, };
