// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Chapter = { id: string, manga_id: string, volume: string | null, chapter: string | null, title: string | null, translated_language: string, scanlator_group: string | null, external_url: string | null, publish_at: string | null, readable_at: string | null, pages: bigint | null, read: boolean, is_new: boolean, };
