// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manga } from "./Manga";

export type FollowedManga = { manga: Manga, preferred_language: string, unread_count: bigint, last_checked_at: string | null, notify_enabled: boolean, unread_chapters: string | null, category_ids: Array<string>, };
