// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";
import type { Manga } from "./Manga";

export type HistoryEntry = { manga: Manga, chapter: Chapter | null, accessed_at: string, entry_type: string, };
