// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MalListStatus = { status: string, score: number, num_volumes_read: number, num_chapters_read: number, };
