// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MalListStatus } from "./MalListStatus";
import type { MalNode } from "./MalNode";

export type MalListItem = { node: MalNode, list_status: MalListStatus, };
