// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MalGenre } from "./MalGenre";
import type { MalPicture } from "./MalPicture";

export type MalRankingManga = { id: bigint, title: string, main_picture: MalPicture | null, mean: number | null, genres: Array<MalGenre> | null, };
