// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Manga = { id: string, title: string, description: string | null, author: string | null, cover_art_id: string | null, cover_filename: string | null, cover_url: string | null, status: string, original_language: string | null, followed: boolean, created_at: string, updated_at: string, mal_id: bigint | null, mal_score: number | null, mal_status: string | null, };
