// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MangaFilters = { original_language: string | null, status: string | null, content_ratings: Array<string>, available_translated_language: string | null, };
