// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadingProgress = { chapter_id: string, page_index: bigint, completed: boolean, updated_at: string, };
